const findEmplStat =`SELECT EMPL_ID,
EMPLOYEE_NAME,
PHONE_HOME,
PHONE_MOBILE,
APPOINTMENT,
OID,
STAFF_NAME,
PLACE_NAME,
PLACE_DESCRIPTION,
OBJ_NAME,
OBJ_NUMBER,
OBJ_DESCRIPTION
 FROM EMPLOYEE INNER JOIN
(SELECT
    EMPL_T.ID AS EMPL_ID,
    EMPL_T.OID AS OID, 
    EMPL_T.NAME AS EMPLOYEE_NAME,
    STAFF_T.NAME AS STAFF_NAME,
    PLACE_T.NAME AS PLACE_NAME,
    CAST(CAST(PLACE_T.DESCRIPTION as blob sub_type text character set binary) AS VARCHAR(210)) AS PLACE_DESCRIPTION,
    OBJ_T.name AS OBJ_NAME, 
    OBJ_T.OID AS OBJ_NUMBER,
    CAST(CAST(OBJ_T.DESCRIPTION as blob sub_type text character set binary) AS VARCHAR(210)) AS OBJ_DESCRIPTION
    FROM
       (SELECT * FROM OBJECTS WHERE CLASS_NAME = 'EMPLOYEE') AS EMPL_T
INNER JOIN  objects as STAFF_T
ON EMPL_T.PARENT_ID = STAFF_T.ID
INNER JOIN OBJECTS AS PLACE_T
ON STAFF_T.PARENT_ID = PLACE_T.ID
INNER JOIN OBJECTS AS OBJ_T
ON PLACE_T.PARENT_ID = OBJ_T.ID) AS OBJECTS
ON EMPLOYEE.ID = OBJECTS.EMPL_ID ORDER BY OID ASC, OBJECTS.EMPL_ID DESC;`


module.exports = {
    findEmplStat
}